### ISSUE TITLE
Option withColumnMenu causes header with filtering to be displayed incorreclty

### ISSUE THREAD

**Issue by pasinski** [zippyui/react-datagrid#237]
I decided not to use the columns visibility toggles. Therefore I wanted to deactivate the columns menu and used the option withColumnMenu setting it to false

````javascript

                <DataGrid
                    dataSource={data}
                    columns={getColumns(columns, t)}
                    pagination={false}
                    loading={loading}
                    style={{height : height}}
                    onFilter={this.handleFilter}
                    liveFilter={true}
                    sortInfo={sortInfo}
                    onSortChange={this.handleSortChange}
                    withColumnMenu={false}
                />

````

This resulted in a very poor look&feel of the whole component rendering a huge filter symbol and disabling the functionality of showing the filter symbol on hover

**Comment by pasinski** [comment]
Following CSS has fixed it for me. It would be great, if someone from zippyui team built it into the stylus files:

````css

.react-datagrid .z-column-header .z-show-filter {
  display: none;
  position: absolute;
  cursor: pointer;
  right: 0px;
  top: 0px;
  width: 15px;
  height: 100%;
  border-left: 1px solid #a8a8a8;
}

.react-datagrid.z-column-header.z-filterable .z-show-filter.z-active .z-show-filter:hover {
  background: #fff;
}

.react-datagrid .z-column-header.z-over.z-filterable .z-show-filter {
  display: block;
}

 
.react-datagrid .z-column-header.z-active.z-filterable .z-show-filter, 
.react-datagrid .z-column-header.z-over .z-show-filter   {
    display : block;
}

.react-datagrid .z-column-header.z-filtered {
  font-style: italic;
}
````
