### ISSUE TITLE
Horizontal Scroll Bar Missing on Windows and Chrome 53

### ISSUE THREAD

**Issue by davertron** [zippyui/react-datagrid#251]
![horizontal-scroll-missing-chrome53-windows](https://cloud.githubusercontent.com/assets/70140/19193344/bdb907b8-8c77-11e6-8e7d-c272f21106bf.png)

Shift scrolling still works though so we're working around it right now that way but definitely makes it confusing for users.

**Comment by davertron** [comment]
Also for what it's worth the scroll bar seems to work fine on the latest version of Firefox for Windows 7.

**Comment by Xuhao** [comment]
Try to modify CSS to fix this:

```css
.z-horizontal-scrollbar {
  // 1. omit transform
  // transform: translate3d(0px, 0px, 1px);

  // 2. assign exact height
  height: 15px;
}
```
